name: Test, Build and Save Artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies run test and generate artifact
        run: |
          npm run build
          # Any other command to set up environment

      # Assuming the .jar files are in the 'build/libs' directory
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: |
            sonar-plugin/sonar-javascript-plugin/target/*.jar